### ISSUE TITLE
Login/registration tests broken.

### ISSUE THREAD

**Issue by elhusseiniali** [elhusseiniali/loki#18]
Login and registration tests seem to be broken: I think the login and register functions defined in the Helper class are not working properly (after a quick debug session, the form.validate_on_submit() clause was not being executed). Most likely this has to do with how WTForms and Bootstrap play together. Ultimately the tests aren't too important, because of how simple the functions are. I would like to have them only for the sake of completion (tests for correct and incorrect login/registration).

**Comment by Gabriel-Faivre** [comment]
Fixed on branch test-gabriel
